### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by cart88** [fire-keeper/BlindWatermark#39]
ValueError: operands could not be broadcast together with shapes

**Comment by cart88** [comment]
[root@master BlindWatermark]# python3 bwm.py -k 4399 2333 32 -ex -r out1.png -wm pic/wm1.png -ws 64 64 -o out_wm.png -s
Namespace(block_shape=4, dwt_deep=1, embed=False, extract=True, key=[4399.0, 2333.0, 32.0], ori_img='out1.png', output='out_wm.png', show_ncc=True, wm='pic/wm1.png', wm_shape=['64', '64'])
Traceback (most recent call last):
  File "bwm.py", line 61, in <module>
    test_ncc(args.wm,args.output)
  File "/root/BlindWatermark/BlindWatermark/ncc.py", line 14, in test_ncc
    print(NCC(a[:,:,i],b[:,:,i]))
  File "/root/BlindWatermark/BlindWatermark/ncc.py", line 6, in NCC
    cross_mul_sum=((A-A.mean())*(B-B.mean())).sum()
ValueError: operands could not be broadcast together with shapes (49,223) (64,64)
